package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.FetchType;

/**
 * Cargos generated by hbm2java
 */
@Entity
@Table(name = "cargos",uniqueConstraints = @UniqueConstraint(
	  columnNames= {"cargo","username"}), catalog = "bddefensoriapublica")
public class Cargos implements java.io.Serializable {

	private int idCargos;
	private UsuarioSistema usuariosistema;
	private String cargo; 


	public Cargos() {
	}

	public Cargos(int idCargos, String cargo,UsuarioSistema usuarioSistema) {
		this.idCargos = idCargos;
		this.usuariosistema=usuarioSistema;
		this.cargo = cargo;
	}
      @ManyToOne(fetch=FetchType.EAGER)
      @JoinColumn(name="username",nullable=false)
	public UsuarioSistema getUsuariosistema() {
		return usuariosistema;
	}

	public void setUsuariosistema(UsuarioSistema usuariosistema) {
		this.usuariosistema = usuariosistema;
	}

	@Id
	@Column(name = "id_cargos", unique = true, nullable = false,length=10)
	public int getIdCargos() {
		return this.idCargos;
	}

	public void setIdCargos(int idCargos) {
		this.idCargos = idCargos;
	}

	@Column(name = "cargo", nullable = false, length = 45)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

}
