package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Defensor generated by hbm2java
 */
@Entity
@Table(name = "defensor", catalog = "bddefensoriapublica")
public class Defensor implements java.io.Serializable {

	private int idDefensor;
	private String noCedulaProfesional;
	private int id_juzgado;
	private int id_estudio;
	
     @OneToOne(mappedBy="Defensor")
	private Personal personal;
	
	public Defensor() {
	}

	public Defensor(int idDefensor, String noCedulaProfesional, int id_juzgado, int id_estudio,
			String regionAdscripcion) {
		this.idDefensor = idDefensor;
		this.noCedulaProfesional = noCedulaProfesional;
		this.id_juzgado = id_juzgado;
		this.id_estudio = id_estudio;
	}

	@Id
//    @GeneratedValue(strategy = GenerationType.AUTO)
     @GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idDefensor", unique = true, nullable = false)
	public int getIdDefensor() {
		return this.idDefensor;
	}

	public void setIdDefensor(int idDefensor) {
		this.idDefensor = idDefensor;
	}

	@Column(name = "id_juzgado", nullable = false, length = 11)
	public int getId_juzgado() {
		return id_juzgado;
	}

	public void setId_juzgado(int id_juzgado) {
		this.id_juzgado = id_juzgado;
	}

	@Column(name = "id_estudio", nullable = false, length = 11)
	public int getId_estudio() {
		return id_estudio;
	}

	public void setId_estudio(int id_estudio) {
		this.id_estudio = id_estudio;
	}

	public void setNoCedulaProfesional(String noCedulaProfesional) {
		this.noCedulaProfesional = noCedulaProfesional;
	}
	

	@Column(name = "no_cedula_profesional", nullable = false)
	public String getNoCedulaProfesional() {
		return this.noCedulaProfesional;
	}

	

	@Override
	public String toString() {
		return "Defensor [idDefensor=" + idDefensor + ", noCedulaProfesional=" + noCedulaProfesional + ", id_juzgado="
				+ id_juzgado + ", id_estudio=" + id_estudio + ", personal=" + personal + "]";
	}




}
