package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleEncuesta generated by hbm2java
 */
@Entity
@Table(name = "detalle_encuesta", catalog = "bddefensoriapublica")
public class DetalleEncuesta implements java.io.Serializable {

	private int idDetalleEncuesta;
	private int idEncuesta;
	private int idUsuarioServicio;

	public DetalleEncuesta() {
	}

	public DetalleEncuesta(int idDetalleEncuesta, int idEncuesta, int idUsuarioServicio) {
		this.idDetalleEncuesta = idDetalleEncuesta;
		this.idEncuesta = idEncuesta;
		this.idUsuarioServicio = idUsuarioServicio;
	}

	@Id

	@Column(name = "idDetalle_Encuesta", unique = true, nullable = false)
	public int getIdDetalleEncuesta() {
		return this.idDetalleEncuesta;
	}

	public void setIdDetalleEncuesta(int idDetalleEncuesta) {
		this.idDetalleEncuesta = idDetalleEncuesta;
	}

	@Column(name = "idEncuesta", nullable = false)
	public int getIdEncuesta() {
		return this.idEncuesta;
	}

	public void setIdEncuesta(int idEncuesta) {
		this.idEncuesta = idEncuesta;
	}

	@Column(name = "idUsuario_Servicio", nullable = false)
	public int getIdUsuarioServicio() {
		return this.idUsuarioServicio;
	}

	public void setIdUsuarioServicio(int idUsuarioServicio) {
		this.idUsuarioServicio = idUsuarioServicio;
	}

}
