package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleExpediente generated by hbm2java
 */
@Entity
@Table(name = "detalle_expediente", catalog = "bddefensoriapublica")
public class DetalleExpediente implements java.io.Serializable {

	private int idDetalleExpediente;
	private int idUsuarioServicio;
	private int idDefensor;

	public DetalleExpediente() {
	}

	public DetalleExpediente(int idDetalleExpediente, int idUsuarioServicio, int idDefensor) {
		this.idDetalleExpediente = idDetalleExpediente;
		this.idUsuarioServicio = idUsuarioServicio;
		this.idDefensor = idDefensor;
	}

	@Id

	@Column(name = "idDetalle_Expediente", unique = true, nullable = false)
	public int getIdDetalleExpediente() {
		return this.idDetalleExpediente;
	}

	public void setIdDetalleExpediente(int idDetalleExpediente) {
		this.idDetalleExpediente = idDetalleExpediente;
	}

	@Column(name = "idUsuario_Servicio", nullable = false)
	public int getIdUsuarioServicio() {
		return this.idUsuarioServicio;
	}

	public void setIdUsuarioServicio(int idUsuarioServicio) {
		this.idUsuarioServicio = idUsuarioServicio;
	}

	@Column(name = "idDefensor", nullable = false)
	public int getIdDefensor() {
		return this.idDefensor;
	}

	public void setIdDefensor(int idDefensor) {
		this.idDefensor = idDefensor;
	}

}
