package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Encuesta generated by hbm2java
 */
@Entity
@Table(name = "encuesta", catalog = "bddefensoriapublica")
public class Encuesta implements java.io.Serializable {

	private int idEncuesta;
	private int idMateria;
	private int idFase;
	private int numeroExpediente;
	private int numeroToca;
	private String juzgadoOrigen;
	private String salaDondeRadica;
	private String nombreApelanteApelado;
	private String delito;
	private String resolucionRecurrida;
	private Date fechaNotificacionAutoinicio;

	public Encuesta() {
	}

	public Encuesta(int idEncuesta, int idMateria, int idFase, int numeroExpediente, int numeroToca,
			String juzgadoOrigen, String salaDondeRadica, String nombreApelanteApelado, String delito,
			String resolucionRecurrida, Date fechaNotificacionAutoinicio) {
		this.idEncuesta = idEncuesta;
		this.idMateria = idMateria;
		this.idFase = idFase;
		this.numeroExpediente = numeroExpediente;
		this.numeroToca = numeroToca;
		this.juzgadoOrigen = juzgadoOrigen;
		this.salaDondeRadica = salaDondeRadica;
		this.nombreApelanteApelado = nombreApelanteApelado;
		this.delito = delito;
		this.resolucionRecurrida = resolucionRecurrida;
		this.fechaNotificacionAutoinicio = fechaNotificacionAutoinicio;
	}

	@Id

	@Column(name = "idEncuesta", unique = true, nullable = false)
	public int getIdEncuesta() {
		return this.idEncuesta;
	}

	public void setIdEncuesta(int idEncuesta) {
		this.idEncuesta = idEncuesta;
	}

	@Column(name = "idMateria", nullable = false)
	public int getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(int idMateria) {
		this.idMateria = idMateria;
	}

	@Column(name = "idFase", nullable = false)
	public int getIdFase() {
		return this.idFase;
	}

	public void setIdFase(int idFase) {
		this.idFase = idFase;
	}

	@Column(name = "numero_expediente", nullable = false)
	public int getNumeroExpediente() {
		return this.numeroExpediente;
	}

	public void setNumeroExpediente(int numeroExpediente) {
		this.numeroExpediente = numeroExpediente;
	}

	@Column(name = "numero_toca", nullable = false)
	public int getNumeroToca() {
		return this.numeroToca;
	}

	public void setNumeroToca(int numeroToca) {
		this.numeroToca = numeroToca;
	}

	@Column(name = "juzgado_origen", nullable = false, length = 45)
	public String getJuzgadoOrigen() {
		return this.juzgadoOrigen;
	}

	public void setJuzgadoOrigen(String juzgadoOrigen) {
		this.juzgadoOrigen = juzgadoOrigen;
	}

	@Column(name = "sala_donde_radica", nullable = false, length = 45)
	public String getSalaDondeRadica() {
		return this.salaDondeRadica;
	}

	public void setSalaDondeRadica(String salaDondeRadica) {
		this.salaDondeRadica = salaDondeRadica;
	}

	@Column(name = "nombre_apelante_apelado", nullable = false, length = 45)
	public String getNombreApelanteApelado() {
		return this.nombreApelanteApelado;
	}

	public void setNombreApelanteApelado(String nombreApelanteApelado) {
		this.nombreApelanteApelado = nombreApelanteApelado;
	}

	@Column(name = "delito", nullable = false, length = 45)
	public String getDelito() {
		return this.delito;
	}

	public void setDelito(String delito) {
		this.delito = delito;
	}

	@Column(name = "resolucion_recurrida", nullable = false, length = 45)
	public String getResolucionRecurrida() {
		return this.resolucionRecurrida;
	}

	public void setResolucionRecurrida(String resolucionRecurrida) {
		this.resolucionRecurrida = resolucionRecurrida;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_notificacion_autoinicio", nullable = false, length = 10)
	public Date getFechaNotificacionAutoinicio() {
		return this.fechaNotificacionAutoinicio;
	}

	public void setFechaNotificacionAutoinicio(Date fechaNotificacionAutoinicio) {
		this.fechaNotificacionAutoinicio = fechaNotificacionAutoinicio;
	}

}
