package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estudios generated by hbm2java
 */
@Entity
@Table(name = "estudios", catalog = "bddefensoriapublica")
public class Estudios implements java.io.Serializable {

	private int idEstudios;
	private int idDefensor;
	private String gradoEstudio;
	private Date fechaTermino;
	private String nombreInstitucionEducativa;
	private String nombrePlanEstudios;
	private String descripcionPerfilEgreso;
	private String documentoProvatorio;

	public Estudios() {
	}

	public Estudios(int idEstudios, int idDefensor, String gradoEstudio, Date fechaTermino,
			String nombreInstitucionEducativa, String nombrePlanEstudios, String descripcionPerfilEgreso,
			String documentoProvatorio) {
		this.idEstudios = idEstudios;
		this.idDefensor = idDefensor;
		this.gradoEstudio = gradoEstudio;
		this.fechaTermino = fechaTermino;
		this.nombreInstitucionEducativa = nombreInstitucionEducativa;
		this.nombrePlanEstudios = nombrePlanEstudios;
		this.descripcionPerfilEgreso = descripcionPerfilEgreso;
		this.documentoProvatorio = documentoProvatorio;
	}

	@Id

	@Column(name = "idEstudios", unique = true, nullable = false)
	public int getIdEstudios() {
		return this.idEstudios;
	}

	public void setIdEstudios(int idEstudios) {
		this.idEstudios = idEstudios;
	}

	@Column(name = "idDefensor", nullable = false)
	public int getIdDefensor() {
		return this.idDefensor;
	}

	public void setIdDefensor(int idDefensor) {
		this.idDefensor = idDefensor;
	}

	@Column(name = "grado_estudio", nullable = false, length = 3)
	public String getGradoEstudio() {
		return this.gradoEstudio;
	}

	public void setGradoEstudio(String gradoEstudio) {
		this.gradoEstudio = gradoEstudio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_termino", nullable = false, length = 10)
	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	@Column(name = "nombre_institucion_educativa", nullable = false, length = 45)
	public String getNombreInstitucionEducativa() {
		return this.nombreInstitucionEducativa;
	}

	public void setNombreInstitucionEducativa(String nombreInstitucionEducativa) {
		this.nombreInstitucionEducativa = nombreInstitucionEducativa;
	}

	@Column(name = "nombre_plan_estudios", nullable = false, length = 45)
	public String getNombrePlanEstudios() {
		return this.nombrePlanEstudios;
	}

	public void setNombrePlanEstudios(String nombrePlanEstudios) {
		this.nombrePlanEstudios = nombrePlanEstudios;
	}

	@Column(name = "descripcion_perfil_egreso", nullable = false, length = 45)
	public String getDescripcionPerfilEgreso() {
		return this.descripcionPerfilEgreso;
	}

	public void setDescripcionPerfilEgreso(String descripcionPerfilEgreso) {
		this.descripcionPerfilEgreso = descripcionPerfilEgreso;
	}

	@Column(name = "documento_provatorio", nullable = false, length = 45)
	public String getDocumentoProvatorio() {
		return this.documentoProvatorio;
	}

	public void setDocumentoProvatorio(String documentoProvatorio) {
		this.documentoProvatorio = documentoProvatorio;
	}

}
