package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name = "materia", catalog = "bddefensoriapublica")
public class Materia implements java.io.Serializable {

	private int idMateria;
	private int idSistema;
	private String materia;

	public Materia() {
	}

	public Materia(int idMateria, int idSistema, String materia) {
		this.idMateria = idMateria;
		this.idSistema = idSistema;
		this.materia = materia;
	}

	@Id

	@Column(name = "idMateria", unique = true, nullable = false)
	public int getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(int idMateria) {
		this.idMateria = idMateria;
	}

	@Column(name = "idSistema", nullable = false)
	public int getIdSistema() {
		return this.idSistema;
	}

	public void setIdSistema(int idSistema) {
		this.idSistema = idSistema;
	}

	@Column(name = "materia", nullable = false, length = 2)
	public String getMateria() {
		return this.materia;
	}

	public void setMateria(String materia) {
		this.materia = materia;
	}

}
