package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reportesxcaso generated by hbm2java
 */
@Entity
@Table(name = "reportesxcaso", catalog = "bddefensoriapublica")
public class Reportesxcaso implements java.io.Serializable {

	private int idReportesXcaso;
	private int idBitacora;
	private Date fechaCaso;

	public Reportesxcaso() {
	}

	public Reportesxcaso(int idReportesXcaso, int idBitacora, Date fechaCaso) {
		this.idReportesXcaso = idReportesXcaso;
		this.idBitacora = idBitacora;
		this.fechaCaso = fechaCaso;
	}

	@Id

	@Column(name = "idReportesXCaso", unique = true, nullable = false)
	public int getIdReportesXcaso() {
		return this.idReportesXcaso;
	}

	public void setIdReportesXcaso(int idReportesXcaso) {
		this.idReportesXcaso = idReportesXcaso;
	}

	@Column(name = "idBitacora", nullable = false)
	public int getIdBitacora() {
		return this.idBitacora;
	}

	public void setIdBitacora(int idBitacora) {
		this.idBitacora = idBitacora;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_caso", nullable = false, length = 10)
	public Date getFechaCaso() {
		return this.fechaCaso;
	}

	public void setFechaCaso(Date fechaCaso) {
		this.fechaCaso = fechaCaso;
	}

}
