package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sistema generated by hbm2java
 */
@Entity
@Table(name = "sistema", catalog = "bddefensoriapublica")
public class Sistema implements java.io.Serializable {

	private int idSistema;
	private String sistema;

	public Sistema() {
	}

	public Sistema(int idSistema, String sistema) {
		this.idSistema = idSistema;
		this.sistema = sistema;
	}

	@Id

	@Column(name = "idSistema", unique = true, nullable = false)
	public int getIdSistema() {
		return this.idSistema;
	}

	public void setIdSistema(int idSistema) {
		this.idSistema = idSistema;
	}

	@Column(name = "sistema", nullable = false, length = 2)
	public String getSistema() {
		return this.sistema;
	}

	public void setSistema(String sistema) {
		this.sistema = sistema;
	}

}
