package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioServicio generated by hbm2java
 */
@Entity
@Table(name = "usuario_servicio", catalog = "bddefensoriapublica")
public class UsuarioServicio implements java.io.Serializable {

	private int idUsuarioServicio;
	private String nombre;
	private String apPaterno;
	private String apMaterno;
	private String sexo;
	private String curp;
	private String lugarNacimiento;
	private Date fechaNacimiento;
	private String telefono;
	private String correoElectronico;
	private String grupoIndigena;
	private String hablaLenguaIndigena;
	private String idiomaLengua;

	public UsuarioServicio() {
	}

	public UsuarioServicio(int idUsuarioServicio, String nombre, String apPaterno, String apMaterno, String sexo,
			String curp, String lugarNacimiento, Date fechaNacimiento, String telefono, String correoElectronico,
			String grupoIndigena, String hablaLenguaIndigena, String idiomaLengua) {
		this.idUsuarioServicio = idUsuarioServicio;
		this.nombre = nombre;
		this.apPaterno = apPaterno;
		this.apMaterno = apMaterno;
		this.sexo = sexo;
		this.curp = curp;
		this.lugarNacimiento = lugarNacimiento;
		this.fechaNacimiento = fechaNacimiento;
		this.telefono = telefono;
		this.correoElectronico = correoElectronico;
		this.grupoIndigena = grupoIndigena;
		this.hablaLenguaIndigena = hablaLenguaIndigena;
		this.idiomaLengua = idiomaLengua;
	}

	@Id

	@Column(name = "idUsuario_Servicio", unique = true, nullable = false)
	public int getIdUsuarioServicio() {
		return this.idUsuarioServicio;
	}

	public void setIdUsuarioServicio(int idUsuarioServicio) {
		this.idUsuarioServicio = idUsuarioServicio;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ap_paterno", nullable = false, length = 45)
	public String getApPaterno() {
		return this.apPaterno;
	}

	public void setApPaterno(String apPaterno) {
		this.apPaterno = apPaterno;
	}

	@Column(name = "ap_materno", nullable = false, length = 45)
	public String getApMaterno() {
		return this.apMaterno;
	}

	public void setApMaterno(String apMaterno) {
		this.apMaterno = apMaterno;
	}

	@Column(name = "sexo", nullable = false, length = 2)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "curp", nullable = false, length = 18)
	public String getCurp() {
		return this.curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}

	@Column(name = "lugar_nacimiento", nullable = false, length = 45)
	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", nullable = false, length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "telefono", nullable = false, length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "correo_electronico", nullable = false, length = 45)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "grupo_indigena", nullable = false, length = 2)
	public String getGrupoIndigena() {
		return this.grupoIndigena;
	}

	public void setGrupoIndigena(String grupoIndigena) {
		this.grupoIndigena = grupoIndigena;
	}

	@Column(name = "habla_lengua_indigena", nullable = false, length = 2)
	public String getHablaLenguaIndigena() {
		return this.hablaLenguaIndigena;
	}

	public void setHablaLenguaIndigena(String hablaLenguaIndigena) {
		this.hablaLenguaIndigena = hablaLenguaIndigena;
	}

	@Column(name = "idioma_lengua", nullable = false, length = 45)
	public String getIdiomaLengua() {
		return this.idiomaLengua;
	}

	public void setIdiomaLengua(String idiomaLengua) {
		this.idiomaLengua = idiomaLengua;
	}

}
